format = """
[](bold purple)$username[@](cyan)$hostname[](purple) \
$directory$git_branch$git_status
$character
"""

[directory]
style = "bold cyan"
truncation_length = 3

[character]
success_symbol = "[❯](bold magenta)"
error_symbol = "[✘](bold red)"
